config/routes.rb
Fitnesstracker::Application.routes.draw do
  resources :exercises

  match 'reports/individualreport' => 'reports#individual_report'
  match 'reports/weeklyreport' => 'reports#weekly_report'
  match 'reports/process_report' => 'reports#process_report'
  match 'reports/personreport' => 'reports#person_report'
  match 'reports/process_person_report' => 'reports#process_person_report'

  root :to => 'exercises#index'

end

app/models/exercise.rb
class Exercise < ActiveRecord::Base
  validates :person, :exercise_date, :minutes, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/exercises_controller.rb
class ExercisesController < ApplicationController
  # GET /exercises
  # GET /exercises.json
  def index
    @exercises = Exercise.find(:all, :order => 'exercise_date DESC')
    @total_count = @exercises.count

    @total_minutes = 0

    @exercises.each do |exercise|
      @total_minutes = @total_minutes + exercise.minutes
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @exercises }
    end
  end

  # GET /exercises/1
  # GET /exercises/1.json
  def show
    @exercise = Exercise.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @exercise }
    end
  end

  # GET /exercises/new
  # GET /exercises/new.json
  def new
    @exercise = Exercise.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @exercise }
    end
  end

  # GET /exercises/1/edit
  def edit
    @exercise = Exercise.find(params[:id])
  end

  # POST /exercises
  # POST /exercises.json
  def create
    @exercise = Exercise.new(params[:exercise])

    respond_to do |format|
      if @exercise.save
        format.html { redirect_to @exercise, notice: 'Exercise was successfully created.' }
        format.json { render json: @exercise, status: :created, location: @exercise }
      else
        format.html { render action: "new" }
        format.json { render json: @exercise.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /exercises/1
  # PUT /exercises/1.json
  def update
    @exercise = Exercise.find(params[:id])

    respond_to do |format|
      if @exercise.update_attributes(params[:exercise])
        format.html { redirect_to @exercise, notice: 'Exercise was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @exercise.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /exercises/1
  # DELETE /exercises/1.json
  def destroy
    @exercise = Exercise.find(params[:id])
    @exercise.destroy

    respond_to do |format|
      format.html { redirect_to exercises_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  def weekly_report
    @start = Date.today
    @end = 7.days.since(Date.today)
  end

  def process_report
    @start = params[:start]
    @end = params[:end]
    @exercises = Exercise.find(:all, :conditions => { :exercise_date => @start..@end })
    
    @total_count = @exercises.count

    @total_minutes = 0

    @exercises.each do |exercise|
      @total_minutes = @total_minutes + exercise.minutes
    end

    if params[:csv] != nil
      send_data(@exercises.to_csv, :type => "text/csv; charset=utf-8; header=present", :filename => "weekly.csv")
      return
    end

    respond_to do |format|
      format.html # process_report.html.erb
      format.json { render json: @exercises }
    end
  end

  def person_report
  end

  def process_person_report
    @person = params[:person]
    @exercises = Exercise.where("person = ?", @person)
    @total_count = @exercises.count

    @total_minutes = 0

    @exercises.each do |exercise|
      @total_minutes = @total_minutes + exercise.minutes
    end

    if params[:csv] != nil
      filename = @person + ".csv"
      send_data(@exercises.to_csv, :type => "text/csv; charset=utf-8; header=present", :filename => filename)
      return
    end

    if params[:pdf] != nil
      pdf = IndividualExercisePdf.new(@exercises)
      send_data pdf.render, filename: "#{@person}.pdf",
                            type: "application/pdf",
                            disposition: "inline"
      return
    end

    respond_to do |format|
      format.html # process_report.html.erb
      format.json { render json: @exercises }
      format.csv { send_data(@exercises.to_csv) }
    end
  end

  def individual_report
    @exercises = Exercise.all.group_by { |e| e.person }
    @total_minutes = 0.0

    Exercise.all.each do |exercise|
      @total_minutes = @total_minutes + exercise.minutes
    end

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
  case level
  when :notice then 'info'
  when :error then 'error'
  when :alert then 'warning'
  end
  end
end

app/helpers/exercises_helper.rb
module ExercisesHelper
end

app/views/exercises/_form.html.erb
<div class="clearfix">
   <%= f.label :person, t("activerecord.attributes.exercise.person", :default => "Person"), :class => :label %>
  <div class="input">
    <%= f.select :person, [['Alex', 'Alex'],
                           ['Ashley', 'Ashley'],
                           ['Beth', 'Beth'],
                           ['Carlos', 'Carlos'],
                           ['Cesar', 'Cesar'],
                           ['Chris', 'Chris'],
                           ['Freeman', 'Freeman'],
                           ['Gordon', 'Gordon'],
                           ['Jaime', 'Jaime'],
                           ['Jim', 'Jim'],
                           ['Joel', 'Joel'],
                           ['Karen', 'Karen'],
                           ['Kevin', 'Kevin'],
                           ['Manjeet', 'Manjeet'],
                           ['Mark', 'Mark'],
                           ['Martavis', 'Martavis'],
                           ['Michael', 'Michael'],
                           ['Roger', 'Roger'],
                           ['Seana', 'Seana'],
                           ['Simmons', 'Simmons'],
                           ['Sosebee', 'Sosebee'],
                           ['Vikki', 'Vikki'],
                           ['Waldon', 'Waldon']] %>
  </div>
</div>

<div class="clearfix">
   <%= f.label :minutes, t("activerecord.attributes.exercise.minutes", :default => "Minutes"), :class => :label %>
  <div class="input">
    <%= f.text_field :minutes, :class => 'text_field' %>
  </div>
</div>

<div class="clearfix">
   <%= f.label :exercise_date, t("activerecord.attributes.exercise.exercise_date", :default => "Exercise date"), :class => :label %>
  <div class="input">
    <%= f.datetime_select :exercise_date, :class => 'datetime_select' %>
  </div>
</div>
<div class="form-actions">
  <button class="btn btn-large btn-success" type="submit">Save</button> or
	<%= link_to "Cancel", exercises_path %>
</div>

app/views/exercises/edit.html.erb
<%= form_for @exercise, :url => exercise_path(@exercise), :html => { :class => "edit_exercise", :id => "edit_exercise" } do |f| -%>
  <input name="_method" type="hidden" value="put" />
  <%= render :partial => "form", :locals => {:f => f} %>
<% end -%>

app/views/exercises/index.html.erb
<h1> <%= @total_count %> Exercises so far...</h1>

<p>
  <h3> <%= @total_minutes %> total minutes</h3>
</p>

<%= link_to '<i class="icon-calendar icon-white"></i> New Exercise'.html_safe, new_exercise_path, :class => 'btn btn-success btn-large' %>

<table class="table table-striped">
 <thead>
  <tr>
    <th>
      <%= t("activerecord.attributes.exercise.person", :default => t("activerecord.labels.person", :default => "Person")) %>
    </th>
        <th>Exercise Date</th>
        <th>Minutes</th>
    <th>Actions</th>
  </tr>
  </thead>
  <tbody>
  <% @exercises.each do |exercise| -%>
   <tr>
    <td><%= link_to exercise.person, exercise_path(exercise) %>
    </td>
        <td><%= exercise.exercise_date.to_date.to_s(:long) %></td>
        <td><%= exercise.minutes %></td>
    <td>
      <%= link_to '<i class="icon-search"></i>'.html_safe, exercise_path(exercise), :class => 'btn btn-small' %>
      <%= link_to '<i class="icon-edit"></i>'.html_safe, edit_exercise_path(exercise), :class => 'btn btn-small' %>
      <%= link_to '<i class="icon-trash"></i>'.html_safe, exercise_path(exercise), :method => :delete, :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}", :class => 'btn btn-small' %>
    </td>
    </tr>
    <% end -%>
   </tbody>
</table>

app/views/exercises/new.html.erb
<%= form_for @exercise, :url => exercises_path, :html => { :class => :form } do |f| -%>
  <%= render :partial => "form", :locals => {:f => f} %>
<% end -%>

app/views/exercises/show.html.erb
<label class="label"><%= t("activerecord.attributes.exercise.person", :default => t("activerecord.labels.person", :default => "Person")) %>:</label>
<p><%= @exercise.person %></p>

<label class="label"><%= t("activerecord.attributes.exercise.minutes", :default => t("activerecord.labels.minutes", :default => "Minutes")) %>:</label>
<p><%= @exercise.minutes %></p>

<label class="label"><%= t("activerecord.attributes.exercise.exercise_date", :default => t("activerecord.labels.exercise_date", :default => "Exercise date")) %>:</label>
<p><%= @exercise.exercise_date %></p>

<div class="form-actions">
<%= link_to '<i class="icon-home"></i> Back'.html_safe, exercises_path, :class => 'btn btn-small' %>
<%= link_to '<i class="icon-edit"></i> Edit'.html_safe, edit_exercise_path(@exercise), :class => 'btn btn-small' %>
<%= link_to '<i class="icon-trash"></i> Delete'.html_safe, exercise_path(@exercise), :method => :delete, :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}", :class => 'btn btn-small' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Dev Fitness Tracker</title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <!-- Le styles -->
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <style>
      body {
        padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
        padding-bottom: 40px;
      }
    </style>

    <!-- Le fav and touch icons -->
    <link href="images/favicon.ico" rel="shortcut icon">
    <link href="images/apple-touch-icon.png" rel="apple-touch-icon">
    <link href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon" sizes="72x72">
    <link href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon" sizes="114x114">
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
          <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="i-bar"></span>
            <span class="i-bar"></span>
            <span class="i-bar"></span>
          </a>
          <a class="brand" href="/">Dev Fitness Tracker</a>
          <div class="nav-collapse collapse" style="height: 0px; ">
            <ul class="nav">
                <li><%= link_to "Weekly Report", "/reports/weeklyreport"  %></li>
                <li><%= link_to "Personal Report", "/reports/personreport"  %></li>
                <li><%= link_to "Individual Battle", "/reports/individualreport"  %></li>
            </ul>
          </div>
        </div>
      </div>
    </div>

    <div class="container-fluid">
       <div class="row-fluid">
        <div class="span9">
          <% [:notice, :error, :alert].each do |level| %>
            <% unless flash[level].blank? %>
              <div data-alert="alert" class="alert alert-<%= flash_class(level) %> fade in">
                <a class="close" data-dismiss="alert" href="#">&times;</a>
                <%= content_tag :p, flash[level] %>
              </div>
            <% end %>
          <% end %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
      </footer>

    </div> <!-- /container -->

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/reports/individual_report.html.erb
<h1>The individual battle</h1>

<table class="table table-striped">
 <thead>
  <tr>
    <th>Person</th>
    <th>Total Minutes</th>
    <th>Percentage</th>
  </tr>
  </thead>
  <tbody>
    <% @exercises.keys.sort.each do |person| %>  
   <tr>
    <td><%= person %></td>
    <td><%= @exercises[person].sum { |e| e.minutes } %></td>
    <td><%= number_to_percentage (@exercises[person].sum { |e| e.minutes } / @total_minutes * 100) %></td>
   </tr>
  <% end %>
   </tbody>
</table>

app/views/reports/person_report.html.erb
<form accept-charset="UTF-8" action="/reports/process_person_report" method="post" class="form">
  	<div class="clearfix">
	   <label class="label" for="person">Person</label>
	  <div class="input">
	  	<select id="person" name="person">
	  		<option value="Alex">Alex</option>
            <option value="Ashley">Ashley</option>
            <option value="Beth">Beth</option>
            <option value="Carlos">Carlos</option>
            <option value="Cesar">Cesar</option>
            <option value="Chris">Chris</option>
            <option value="Freeman">Freeman</option>
            <option value="Gordon">Gordon</option>
            <option value="Jaime">Jaime</option>
            <option value="Jim">Jim</option>
            <option value="Joel">Joel</option>
            <option value="Karen">Karen</option>
	    	<option value="Kevin">Kevin</option>
            <option value="Manjeet">Manjeet</option>
            <option value="Mark">Mark</option>
            <option value="Martavis">Martavis</option>
            <option value="Michael">Michael</option>
            <option value="Roger">Roger</option>
            <option value="Seana">Seana</option>
            <option value="Simmons">Simmons</option>
	    	<option value="Sosebee">Sosebee</option>
            <option value="Vikki">Vikki</option>
            <option value="Waldon">Waldon</option>
		</select>
	  </div>
	</div>

	<label class="checkbox">
      <input type="checkbox" id="csv" name="csv"> Generate CSV
    </label>

	<label class="checkbox">
      <input type="checkbox" id="pdf" name="pdf"> Generate PDF
    </label>
    
	<div class="form-actions">
	  <button class="btn btn-large btn-success" type="submit">Run Report</button>
	</div>
</form>

app/views/reports/process_person_report.html.erb
<h1> <%= @total_count %> Exercises for <%= @person %></h1>

<p>
  <h3> <%= @total_minutes %> total minutes</h3>
</p>

<table class="table table-striped">
 <thead>
  <tr>
    <th>
      <%= t("activerecord.attributes.exercise.person", :default => t("activerecord.labels.person", :default => "Person")) %>
    </th>
        <th>Exercise Date</th>
        <th>Minutes</th>
    <th>Actions</th>
  </tr>
  </thead>
  <tbody>
  <% @exercises.each do |exercise| -%>
   <tr>
    <td><%= link_to exercise.person, exercise_path(exercise) %>
    </td>
        <td><%= exercise.exercise_date %></td>
        <td><%= exercise.minutes %></td>
    <td>
      <%= link_to '<i class="icon-search"></i> Show'.html_safe, exercise_path(exercise), :class => 'btn btn-small' %>
      <%= link_to '<i class="icon-edit"></i> Edit'.html_safe, edit_exercise_path(exercise), :class => 'btn btn-small' %>
      <%= link_to '<i class="icon-trash"></i> Delete'.html_safe, exercise_path(exercise), :method => :delete, :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}", :class => 'btn btn-small' %>
    </td>
    </tr>
    <% end -%>
   </tbody>
</table>

app/views/reports/process_report.html.erb
<h1> <%= @total_count %> Exercises between <%= @start %> and <%= @end %></h1>

<p>
  <h3> <%= @total_minutes %> total minutes</h3>
</p>

<table class="table table-striped">
 <thead>
  <tr>
    <th>
      <%= t("activerecord.attributes.exercise.person", :default => t("activerecord.labels.person", :default => "Person")) %>
    </th>
        <th>Exercise Date</th>
        <th>Minutes</th>
    <th>Actions</th>
  </tr>
  </thead>
  <tbody>
  <% @exercises.each do |exercise| -%>
   <tr>
    <td><%= link_to exercise.person, exercise_path(exercise) %>
    </td>
        <td><%= exercise.exercise_date %></td>
        <td><%= exercise.minutes %></td>
    <td>
      <%= link_to '<i class="icon-search"></i> Show'.html_safe, exercise_path(exercise), :class => 'btn btn-small' %>
      <%= link_to '<i class="icon-edit"></i> Edit'.html_safe, edit_exercise_path(exercise), :class => 'btn btn-small' %>
      <%= link_to '<i class="icon-trash"></i> Delete'.html_safe, exercise_path(exercise), :method => :delete, :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}", :class => 'btn btn-small' %>
    </td>
    </tr>
    <% end -%>
   </tbody>
</table>

app/views/reports/weekly_report.html.erb
<form accept-charset="UTF-8" action="/reports/process_report" method="post" class="form">
  	<div class="clearfix">
	   <label class="label" for="start">Start Date</label>
	  <div class="input">
	    <input class="text_field" id="start" name="start" size="30" type="text" value="<%= @start %>">
	  </div>
	</div>

  	<div class="clearfix">
	   <label class="label" for="end">End Date</label>
	  <div class="input">
	    <input class="text_field" id="end" name="end" size="30" type="text" value="<%= @end %>">
	  </div>
	</div>

	<label class="checkbox">
      <input type="checkbox" id="csv" name="csv"> Generate CSV
    </label>

	<div class="form-actions">
	  <button class="btn btn-large btn-success" type="submit">Run Report</button>
	</div>
</form>